# Generated by Django 2.2.1 on 2019-05-15 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escriba el nombre', max_length=45)),
                ('email', models.EmailField(help_text='Escriba el Email', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Escriba el Titulo de la entrada', max_length=100)),
                ('descripcion', models.CharField(help_text='Escriba la entrada', max_length=4000)),
                ('fecha_pub', models.DateField(auto_now=True)),
                ('creador', models.ForeignKey(help_text='Seleccione el Creador', on_delete=django.db.models.deletion.CASCADE, to='blog.Creador')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('fecha_com', models.DateField(auto_now=True)),
                ('descripcion', models.CharField(max_length=1000)),
                ('puntuacion', models.IntegerField()),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Publicacion')),
            ],
        ),
    ]
